### ISSUE TITLE
Aeron-archive takes too long to delete large recordings

### ISSUE THREAD

**Issue by asirir** [G-Research/aeron#1153]
Hello,

We have a service which upon startup deletes all its previous recordings to preserve space. But this operation is timing out within the AMD and taking out the entire archiving conductor with it:
```
io.aeron.exceptions.ConductorServiceTimeoutException: service interval exceeded (ns): timeout=20000000000, interval=20306810997
        at io.aeron.ClientConductor.checkServiceInterval(ClientConductor.java:1089)
        at io.aeron.ClientConductor.checkTimeouts(ClientConductor.java:1072)
        at io.aeron.ClientConductor.service(ClientConductor.java:990)
        at io.aeron.ClientConductor.doWork(ClientConductor.java:191)
        at org.agrona.concurrent.AgentInvoker.invoke(AgentInvoker.java:142)
        at io.aeron.archive.ArchiveConductor.invokeAeronInvoker(ArchiveConductor.java:271)
        at io.aeron.archive.SharedModeArchiveConductor.doWork(SharedModeArchiveConductor.java:57)
        at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
        at java.lang.Thread.run(Thread.java:748)
...
 io.aeron.archive.client.ArchiveException: recording events publication is closed
        at io.aeron.archive.RecordingEventsProxy.checkResult(RecordingEventsProxy.java:142)
        at io.aeron.archive.RecordingEventsProxy.progress(RecordingEventsProxy.java:103)
        at io.aeron.archive.RecordingSession.record(RecordingSession.java:234)
        at io.aeron.archive.RecordingSession.doWork(RecordingSession.java:149)
        at io.aeron.archive.SessionWorker.doWork(SessionWorker.java:58)
        at org.agrona.concurrent.AgentInvoker.invoke(AgentInvoker.java:142)
        at io.aeron.archive.SharedModeArchiveConductor.doWork(SharedModeArchiveConductor.java:59)
        at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
        at java.lang.Thread.run(Thread.java:748)
...
 org.agrona.concurrent.AgentTerminationException
        at io.aeron.ClientConductor.doWork(ClientConductor.java:188)
        at org.agrona.concurrent.AgentInvoker.invoke(AgentInvoker.java:142)
        at io.aeron.archive.ArchiveConductor.invokeAeronInvoker(ArchiveConductor.java:271)
        at io.aeron.archive.SharedModeArchiveConductor.doWork(SharedModeArchiveConductor.java:60)
        at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
        at java.lang.Thread.run(Thread.java:748)
...
 org.agrona.concurrent.AgentTerminationException: unexpected Aeron close
        at io.aeron.archive.ArchiveConductor.invokeAeronInvoker(ArchiveConductor.java:276)
        at io.aeron.archive.SharedModeArchiveConductor.doWork(SharedModeArchiveConductor.java:60)
        at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
        at java.lang.Thread.run(Thread.java:748)
```

It looks like it's the timeout that leads to the other problems. We can raise this timeout - but we are on really fast SSDs and the recoding could not have been more than 400GB at max. We think it should not take this long 20s to delete that recording - also, it seems a bit unreasonable that during this operation (deleting of the recording), the conductor is not being serviced.

Note that we are using the single-thread (back-off strategy) mode for the archiver (+dedicated spinning threads for the main media driver). We could potentially fix the problem by giving more threads to the archiver as well - but we'd prefer not to do that if possible.

Can you please make the single-backoff-thread archiver not blow up in this particular case?

Many thanks.

/ Asiri

**Comment by asirir** [comment]
Our aeron version is: ```aeron-all-1.29.0.jar```

**Comment by mjpt777** [comment]
Is this Windows or Linux, and which version of OS and Java?

**Comment by asirir** [comment]
Hi Martin,

This was on RHEL 7.7 (Kernel 3.10)
Java: OpenJDK 1.8.0_242-b08

Thanks.

**Comment by mjpt777** [comment]
Thanks @asirir. So to confirm you are calling one of the API methods that results in segments being deleted and this is taking a long time? Which method is it and what is your segment file length? 

I've an idea for how to make the segment delete asynchronous and allow the conductor to remain responsive.

**Comment by asirir** [comment]
Hi @mjpt777,

We're invoking ```aeron::archive::client::AeronArchvie::truncateRecording(<recording_id>, 0)```

The recording must have been ~400GB at the time. We are on fast SSDs, but it still took ~20s. As you propose, It would be ideal if the delete operation can be made asynchronous so that the archiving conductor does not get starved.

Thanks!

/ Asiri

**Comment by mjpt777** [comment]
I've changed how segment files are deleted so they are done in their own session so the archive conductor stays responsive.

https://github.com/real-logic/aeron/commit/dc5a3d5425e5a7c79d0242f727a7e09a03aca254

**Comment by mjpt777** [comment]
When deleting files there are some things to be aware off with some file systems and how they implement `discard`, depending on how they are mounted. This is worth a read. https://lwn.net/Articles/787272/

**Comment by asirir** [comment]
Thanks Martin!

**Comment by mjpt777** [comment]
Since the delete segments operation is asynchronous you need to be careful of truncating a recording and then extending it again. If you do then you need to use the new `RecordingSignal.DELETE` to await its completion. https://github.com/real-logic/aeron/commit/d2d44bfbc2b06924562f07bf6f38772bc8fd9886
